### ISSUE TITLE
ApiError: 301002 - Rpc error response

### ISSUE THREAD

**Issue by HaxXorHardy** [garrettjoecox/tarkov-scripts#2]
Yesterday everything worked fine, but today i get an errormsg.
The game is working fine and my other bot is working too.

```
C:\Windows\system32>tarkov auto
Access token expired, refreshing
ApiError: 301002 - Rpc error response
    at Object.<anonymous> (C:\tarkov-scripts-master\dist\api\index.js:47:32)
    at Generator.next (<anonymous>)
    at fulfilled (C:\tarkov-scripts-master\dist\api\index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'ApiError'
}

**Comment by garrettjoecox** [comment]
This means your auth token has expired, you’ll need to run the tarkov auth command again.

**Comment by garrettjoecox** [comment]
Actually, the auto command should be refreshing automatically.. I’m not sure what that error is about, I would try going through the auth process again.

I’m not able to debug anything till I get another account

**Comment by HaxXorHardy** [comment]
How can i contact you? I would donate you a Key.
Edit: i send have send an e-mail.

**Comment by garrettjoecox** [comment]
@HaxXorHardy dude you're awesome! I appreciate it, I'll look into debugging this later tonight

**Comment by HaxXorHardy** [comment]
no problem :) keep your nice work up! 

`tarkov auth`
solved the problem. thx

**Comment by HaxXorHardy** [comment]
and now im banned too :D

**Comment by garrettjoecox** [comment]
Dang... I probably should deprecate the `auto` command, as it seems people are being banned for selling items back to the traders, and people aren't banned for selling back on the marketplace.

**Comment by garrettjoecox** [comment]
Going to close this issue as it seems re authenticating fixed the issue
